config/routes.rb
Rails.application.routes.draw do

  resources :pessoas

  resources :users

  match 'users/:id/cancelar' => 'users#cancelar', via: [:patch, :put], as: :users_cancelar
  match 'users/:id/ativar' => 'users#ativar', via: [:patch, :put], as: :users_ativar
  
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  root 'sessions#new'

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
	has_many :grupo_permissoes
	has_many :permissoes, :through => :grupo_permissoes
	has_many :users

	enum status: [:ativo, :bloqueado]
end

app/models/grupo_permissao.rb
class GrupoPermissao < ActiveRecord::Base
	belongs_to :grupo
	belongs_to :permissao



end

app/models/permissao.rb
class Permissao < ActiveRecord::Base
	has_many :grupo_permissoes
	has_many :grupos, :through => :grupo_permissoes

	enum tipo: [:simnao, :acesso]
	enum modulo: [:usuario]
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
	has_one :user

	validates :nome, presence: true, length: {minimum: 2}
	validates :sobrenome, presence: true, length: {minimum: 2}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	belongs_to :pessoa
	belongs_to :grupo

	validates_presence_of :pessoa
	validates_associated :pessoa

	validates :password, presence: true, length: {minimum: 6}
	validates :login, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}
	before_save {self.login = login.downcase}

	accepts_nested_attributes_for :pessoa, :reject_if => proc { |pessoa| pessoa['nome'].blank? || pessoa['sobrenome'].blank? }

	enum status: [:ativo, :bloqueado]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def authorize
  	unless logged_in?
  		redirect_to root_url
  	end
  end

  def correct_user?
  	@user = User.find(params[:id])
  	unless current_user == @user
  		redirect_to users_path
  	end
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
	before_action :authorize

	def show
		@pessoa = Pessoa.find(params[:id])
	end
	
	def edit
		@pessoa = Pessoa.find(params[:id])
	end

	def update
		@pessoa = Pessoa.find(params[:id])
		if @pessoa.update_attributes(pessoa_params)
			redirect_to users_path
		else
			render action: :edit
		end
	end

	private

	def pessoa_params
		params.require(:pessoa).permit(:nome, :sobrenome)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_access, except: [:destroy]
  layout "login"

  def create
  	@user = User.find_by(login: params[:session][:login].downcase)
  	if @user && @user.authenticate(params[:session][:password])
  		if @user.ativo?
        sign_in
        if @user.grupo.is_root
          redirect_to users_path
        else
          redirect_to @user.pessoa
        end
      else
        render 'new'
      end
  	else
  		render 'new'
  	end
  end

  def destroy
  	sign_out
  	redirect_to root_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorize, except: [:new, :create]
	before_action :correct_user?, only: [:edit, :update, :destroy]

	def new
		@user = User.new
		@user.pessoa = Pessoa.new
		@user.grupo = Grupo.find_by descricao: 'Usuario'
		@grupos = Grupo.all
	end

	def create
		@user = User.new(user_params)
		@user.status = User.status[:ativo]
		@user.grupo = Grupo.find_by descricao: 'Usuario'

		if @user.save
			redirect_to @user.pessoa, notice: "Usuário foi criado com sucesso!"
			sign_in
		else
			render action: :new
		end

	end

	def index
		if current_user.grupo.is_root
			@users = User.all
		else
			@users = User.joins(:grupo).where(grupos: {is_root: false})
		end
	end

	def show
	end

	def edit
		@user = User.find(params[:id])
		@grupos = Grupo.all
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(login: user_params[:login], password: user_params[:password], password_confirmation: user_params[:password_confirmation], grupo_id: user_params[:grupo_id])
			redirect_to users_path
		else
			render action: :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		sign_out
		redirect_to root_path
	end

	def cancelar
		@user = User.find(params[:id])
		@user.update_attribute(:status, User.statuses[:bloqueado])
		redirect_to users_path
	end

	def ativar
		@user = User.find(params[:id])
		@user.update_attribute(:status, User.statuses[:ativo])
		redirect_to users_path
	end

	private
	
	def user_params
		params.require(:user).permit(:login, :password, :password_confirmation, :status, :grupo_id, :pessoa_attributes => [:nome, :sobrenome])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include SessionsHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in
		session[:user_id] = @user.id
	end

	def sign_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def block_access
		if current_user.present?
			redirect_to users_path
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def tem_permissao(chave)
		permissao = Permissao.find_by(chave: chave)
		gp = current_user.grupo.grupo_permissoes.where(permissao_id: permissao.id)
		if (permissao.acesso?)
			if gp.first.valor == "A"
				true
			end
		elsif (permissao.simnao?)
			if gp.first.valor == "S"
				true
			end
		else
			false
		end
	end

	def eval_permissao(chave, valor)
		permissao = Permissao.find_by(chave: chave)
		gp = current_user.grupo.grupo_permissoes.where(permissao_id: permissao.id)
		if (gp.valor != valor)
			true
		else
			false
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.erb
<!-- Page Sidebar -->
<div class="page-sidebar" id="sidebar">
  <!-- Page Sidebar Header-->
  <div class="sidebar-header-wrapper">
    <input type="text" class="searchinput" />
    <i class="searchicon fa fa-search"></i>
    <div class="searchhelper">Search Reports, Charts, Emails or Notifications</div>
  </div>
  <!-- /Page Sidebar Header -->
  <!-- Sidebar Menu -->
  <ul class="nav sidebar-menu">
    <!--Dashboard-->
    <li class="active">
      <a href="index.html">
        <i class="menu-icon fa fa-home"></i>
        <span class="menu-text"> Dashboard </span>
      </a>
    </li>
    <!--Usuários-->
    <% if tem_permissao('permissaoUsuarios') %>
        <li>
          <%= link_to users_path do %>
              <i class="menu-icon fa fa-user"></i>
              <span class="menu-text"> Usuários </span>
          <% end %>
        </li>
    <% end %>
  </ul>
  <!-- /Sidebar Menu -->
</div>
<!-- /Page Sidebar -->

app/views/layouts/_navbar.html.erb
<!--  /Loading Container -->
<!-- Navbar -->
<div class="navbar">
  <div class="navbar-inner">
    <div class="navbar-container">
      <!-- Navbar Barnd -->
      <div class="navbar-header pull-left">
        <a href="#" class="navbar-brand">
          <small>
            <img src="../../../vendor/assets/img/logo.png" alt="" />
          </small>
        </a>
      </div>
      <!-- /Navbar Barnd -->
      <!-- Sidebar Collapse -->
      <div class="sidebar-collapse" id="sidebar-collapse">
        <i class="collapse-icon fa fa-bars"></i>
      </div>
      <!-- /Sidebar Collapse -->
      <!-- Account Area and Settings --->
      <div class="navbar-header pull-right">
        <div class="navbar-account">
          <ul class="account-area">
            <li>
              <a class="login-area dropdown-toggle" data-toggle="dropdown">
                <section>
                  <h2><span class="profile"><span>David Stevenson</span></span></h2>
                </section>
              </a>
              <!--Login Area Dropdown-->
              <ul class="pull-right dropdown-menu dropdown-arrow dropdown-login-area">
                <li class="username"><a>David Stevenson</a></li>
                <li class="email"><a>David.Stevenson@live.com</a></li>
                <li class="edit">
                  <%= link_to 'Perfil', current_user.pessoa, class: 'pull-left' %>
                  <%= link_to 'Editar', edit_pessoa_path(current_user.pessoa), class: 'pull-right' %>
                </li>
                <li class="dropdown-footer">
                  <%= link_to 'Sign out', sign_out_path, method: 'delete' %>
                </li>
              </ul>
              <!--/Login Area Dropdown-->
            </li>
            <!-- /Account Area -->
            <!--Note: notice that setting div must start right after account area list.
            no space must be between these elements-->
            <!-- Settings -->
          </ul><div class="setting">
          <a id="btn-setting" title="Setting" href="#">
            <i class="icon glyphicon glyphicon-cog"></i>
          </a>
        </div><div class="setting-container">
          <label>
            <input type="checkbox" id="checkbox_fixednavbar">
            <span class="text">Fixed Navbar</span>
          </label>
          <label>
            <input type="checkbox" id="checkbox_fixedsidebar">
            <span class="text">Fixed SideBar</span>
          </label>
          <label>
            <input type="checkbox" id="checkbox_fixedbreadcrumbs">
            <span class="text">Fixed BreadCrumbs</span>
          </label>
          <label>
            <input type="checkbox" id="checkbox_fixedheader">
            <span class="text">Fixed Header</span>
          </label>
        </div>
          <!-- Settings -->
        </div>
      </div>
      <!-- /Account Area and Settings -->
    </div>
  </div>
</div>
<!-- /Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Rorbaseproject</title>

  <!--Fonts-->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Roboto:400,300" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Loading Container -->
<div class="loading-container">
  <div class="loader"></div>
</div>
<%= render 'layouts/navbar' %>

<!-- Main Container -->
<div class="main-container container-fluid">
  <!-- Page Container -->
  <div class="page-container">

    <%= render 'layouts/menu' %>

    <div class="page-content">

      <!-- Page Breadcrumb -->
      <div class="page-breadcrumbs">
        <ul class="breadcrumb">
          <li class="active">
            <i class="fa fa-home"></i>
            Dashboard
          </li>
        </ul>
      </div>
      <!-- /Page Breadcrumb -->

      <!-- Page Body -->
      <div class="page-body">

        <%= yield %>

      </div>
      <!-- /Page Body -->

    </div>

  </div>
  <!-- /Page Container -->
</div>
<!-- /Main Container -->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rorbaseproject</title>

  <!--Fonts-->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Roboto:400,300" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/pessoas/edit.html.erb
<h1>Editar perfil</h1>
<%= form_for @pessoa do |f| %>
	<% if @pessoa.errors.any? %>
		<div id="error_explanation">
			<div class="alert-error">
				O formulário contém <%= pluralize(@pessoa.errors.count, "erro") %>.
			</div>
			<ul>
				<% @pessoa.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label :nome %>
		<%= f.text_field :nome %>
	</div>

	<div class="field">
		<%= f.label :sobrenome %>
		<%= f.text_field :sobrenome %>
	</div>

	<% if current_user == @pessoa.user %>
		<%= link_to "Opcoes de Conta", edit_user_path() %>
	<% end %>

	<div class="actions">
		<%= f.submit "Cadastrar"%>
	</div>
<% end %>

app/views/pessoas/show.html.erb
<html>
	<body>
		<h3> Perfil de <%= @pessoa.nome %> </h3>

		<ul>
			<li><%= link_to "Editar", edit_pessoa_path(@pessoa) %></li>
		</ul>
	</body>
</html>

app/views/users/edit.html.erb
<h1>Editar Usuario</h1>
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<div class="alert-error">
				O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
			</div>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label :login %>
		<%= f.text_field :login %>
	</div>
	
	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>
	
	<% if logged_in? && current_user.grupo.is_root %>
		<div class="field">
			<%= f.label :grupo %>
			<%= f.collection_select(:grupo_id, Grupo.all, :id, :descricao) %>
		</div>
	<% else %>
		<%= f.hidden_field :grupo_id, :value => @user.grupo.id %>
	<% end %>

	<div class="actions">
		<%= f.submit "Cadastrar"%>
	</div>
<% end %>

<ul>
	<li><%= link_to "Apagar", @user, method: :delete%></li>
</ul>

app/views/users/index.html.erb
<h1> Users </h1>
<table class="table table-hover table-bordered">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Login</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.pessoa.nome %> <%= user.pessoa.sobrenome %></td>
				<td><%= user.login %></td>
				<td>
					<% if (tem_permissao('permissaoUsuarios') || current_user == user) %>
						<%= link_to "Editar", edit_pessoa_path(user.pessoa) %>
					<% end %>
				</td>
				<td><%= link_to "Visualizar", user.pessoa %></td>
				<td>
					<%if user.ativo?%>
						<%= link_to "Cancelar", users_cancelar_path(:id => user.id), method: :patch %>
					<%else%>
						<%= link_to "Ativar", users_ativar_path(:id => user.id), method: :patch %>
					<%end%>
				</td>
			</tr>
		<%end%>
	</tbody>
</table>

app/views/users/new.html.erb
<h1>Cadastre-se</h1>
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<div class="alert-error">
				O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
			</div>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<%= f.fields_for :pessoa, @user.pessoa do |p| %>
		<div class="field">
			<%= p.label :nome %>
			<%= p.text_field :nome %>
		</div>

		<div class="field">
			<%= p.label :sobrenome %>
			<%= p.text_field :sobrenome %>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label :login %>
		<%= f.text_field :login %>
	</div>
	
	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>
	
	<% if logged_in? && current_user.grupo.is_root %>
		<div class="field">
			<%= f.label :grupo %>
			<%= f.collection_select(:grupo_id, Grupo.all, :id, :descricao) %>
		</div>
	<% else %>
		<%= f.hidden_field :grupo_id, :value => @user.grupo.id %>
	<% end %>

	<div class="actions">
		<%= f.submit "Cadastrar"%>
	</div>
<% end %>

app/views/users/show.html.erb
<html>
	<body>
		<h3> Perfil de <%= @user.pessoa.nome %> </h3>

		<% if current_user == @user %>
			<ul>
				<li><%= link_to "Editar", edit_user_path(current_user) %></li>
				<li><%= link_to "Apagar", @user, method: :delete%></li>
			</ul>
		<%end%>
	</body>
</html>